version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    user: postgres
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rest_with_springboot_erudio
    ports:
      - 5435:5432
    networks:
      - erudio-network
  rest-with-spring-boot-erudio:
    image: joaobuss/rest-with-spring-boot-erudio
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/rest_with_springboot_erudio
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres
    build: ./java-spring-curso
    working_dir: /java-spring-curso
    ports:
      - 9090:9090
    command: mvn spring-boot:run
    networks:
      - erudio-network
    depends_on:
      - db
networks:
  erudio-network:
    driver: bridge